### ISSUE TITLE
关于XES3G5M数据集

### ISSUE THREAD

**Issue by Yumo216** [ZhijieXiong/dlkt#1]
感谢您的工作，我最近正在关注于XES3G5M数据集，但是在DKT上复现的结果和您不太一致。请问如果方便的话，可否添加Wechat，想向您请教讨论一下

**Comment by ZhijieXiong** [comment]
我也看过今年的工作（DGEKT），是非常有新意的想法，我也从中学到了很多。我的微信号是xzjstc13579，很期望能和您交流讨论
