### ISSUE TITLE
关于其他模型的复现情况

### ISSUE THREAD

**Issue by Yumo216** [ZhijieXiong/dlkt#2]
感谢您杰出的工作，最近一直在使用您的代码复现实验结果。最让我关注的就是关于“一题多概念”时您和pyKT不同的处理方法。
您在文档中提到“We currently only implement average pooling of concepts on DKT, AKT, SimpleKT, DIMKT, and QIKT models.”。所以如果我想要复现其他经典模型，如“DKVMN、SAKT”等，是不是还无法实现呢。
期待您的指教

**Comment by ZhijieXiong** [comment]
是的，DKT可以在任意数据格式（only_question, single_concept, multi_concept）下运行，但是DKVMN和SAKT（这是已经重构过一次的代码，今天看到您的问题才把SAKT从旧的代码仓库中迁移过来，如果您想使用SAKT，请pull最新代码，或者从仓库中把对应代码——"example/train/sakt.py", "example/train/config/sakt_config.py", "lib/model/SAKT.py"——拷贝到您的项目下，即可运行）只能在single_concept和multi_concept（data loader中有concept_seq）这两种数据格式下运行；并且DKT可以指定使用question还是concept建模，DKVMN和SAKT不行，只能使用concept，如果您想在这两个模型上实现“一题多概念”，可以参考DKT的实现来更改代码

**Comment by ZhijieXiong** [comment]
> 感谢您杰出的工作，最近一直在使用您的代码复现实验结果。最让我关注的就是关于“一题多概念”时您和pyKT不同的处理方法。 您在文档中提到“We currently only implement average pooling of concepts on DKT, AKT, SimpleKT, DIMKT, and QIKT models.”。所以如果我想要复现其他经典模型，如“DKVMN、SAKT”等，是不是还无法实现呢。 期待您的指教

我今天更改了一下DKVMN和SAKT的代码，已经可以在“一题多概念”下的数据集（如Assist2009、Ednet-kt1）运行了，只是DKVMN可以选择使用question或者还是concept作为id，但是SAKT只能使用concept。具体来说对于多知识点习题，还是用的平均池化获得其concept emb以及interaction emb。感谢您提出的建议

**Comment by ZhijieXiong** [comment]
> > 感谢您杰出的工作，最近一直在使用您的代码复现实验结果。最让我关注的就是关于“一题多概念”时您和pyKT不同的处理方法。 您在文档中提到“We currently only implement average pooling of concepts on DKT, AKT, SimpleKT, DIMKT, and QIKT models.”。所以如果我想要复现其他经典模型，如“DKVMN、SAKT”等，是不是还无法实现呢。 期待您的指教
> 
> 我今天更改了一下DKVMN和SAKT的代码，已经可以在“一题多概念”下的数据集（如Assist2009、Ednet-kt1）运行了，只是DKVMN可以选择使用question或者还是concept作为id，但是SAKT只能使用concept。具体来说对于多知识点习题，还是用的平均池化获得其concept emb以及interaction emb。感谢您提出的建议

这两部分只更改了model的代码，其它地方并没有变化，所以如果您不想pull最新代码，可以只复制这两个model的实现代码

**Comment by Yumo216** [comment]
非常感谢您的积极应对，对我帮助很大。我有问题再向您请教

**Comment by ZhijieXiong** [comment]
> 非常感谢您的积极应对，对我帮助很大。我有问题再向您请教

之前版本DKT跑single_concept数据集（如Assist2012），如果使用了细粒度评估，有bug，目前最新版本已修复，就是model/DKT.py中get_predict_score_seq_len_minus1方法有问题，如果您遇到这个问题，可以从代码仓库中复制这个函数进行替换，其它现有方法应该都是没问题了，只要不是运行assist2015和POJ这两个数据集（只有习题id，没有知识点id，这一类数据集我没怎么考虑，因为现在的方法基本都是两种信息都用）

**Comment by ZhijieXiong** [comment]
打扰了，我们已经将所有代码迁移到PyEdmine：https://github.com/ZhijieXiong/pyedmine 下了，并且开源了榜单上所有模型的参数和权重。如果您目前还在使用dlkt进行实验，推荐您迁移到PyEdmine中，PyEdmine提供了更多功能，包括可以基于wandb记录实验和可以不同角度的指标进行模型评估
